Add Dagger-Hilt plugins and dependencies, add converter gson (close #13, close #8)
timacosta/PokeArch pull request #22
Opened 2023-10-27 09:55 UTC by Mj-br

# Issue #13

- Agregar plugins y librerías de Dagger-Hilt

# Issue #8 

- Agregar converter gson a las librerías

# Comentarios

- Añadir comentarios (se puede borrar si no gusta)

- Cambio de la versión de Java a 17

2023-10-27 12:04 UTC, Mj-br commented on app/build.gradle.kts
> +    id ("kotlin-kapt")
Chicos no sabía como agregar este plugin pero ya lo he solucionado. Está en el commit siguiente.

2023-10-27 12:06 UTC, Mj-br commented on app/build.gradle.kts
> +    kotlin("kapt")
Aquí he puesto el plugin tal cual como se recomienda en la documentación.

2023-10-28 08:13 UTC, JuJoDevs commented on app/build.gradle.kts
> +    kotlin("kapt")
Cambia Kapt por KSP
[Migrate from kapt to KSP](https://developer.android.com/build/migrate-to-ksp)

2023-10-28 08:17 UTC, JuJoDevs requested changes
Cambia Kapt por KSP
[Migrate from kapt to KSP](https://developer.android.com/build/migrate-to-ksp)

2023-10-28 11:12 UTC, JuJoDevs approved these changes

2023-10-28 11:13 UTC, JuJoDevs approved these changes

2023-10-28 11:14 UTC, Mj-br reviewed
Hecho el cambio en vivo. Todo perfecto.

2023-10-30 17:04 UTC, timacosta commented on gradle/libs.versions.toml
> +#Kotlin-Kapt
renombrar el comment a ksp

2023-10-30 20:09 UTC, JuJoDevs approved these changes

2023-10-30 20:10 UTC, Gascanio101 approved these changes

2023-10-30 20:11 UTC, merged