Gabriel #5 scaffold
timacosta/PokeArch pull request #25
Opened 2023-10-30 19:18 UTC by Gascanio101

Añadido el esqueleto del Scaffold. 
Falta String resources y Colores.

2023-11-04 13:57 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/Scaffold.kt
> +fun MyBottomAppBar(vm: MainViewModel) {
Voy a cambiar el BottomBar para que no haga falta este parámetro MainViewModel. 

Lo haremos así para quitarle esta responsabilidad al ViewModel.

2023-11-04 13:58 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/Scaffold.kt
> +fun MainTopAppBar(vm: MainViewModel) {
De momento no vamos a usar Top Bar. Podemos hablarlo de añadirlo mas adelante en caso que queramos.

2023-11-04 13:59 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/PokeArchActivity.kt
> +                    MyScaffold(vm)
Vamos a intentar que quede como está en develop sin necesidad de cambiar esta parte.

Tenemos que estar siempre actualizados con la rama develop para evitar estos casos.

Me pasaba lo mismo antes, no te preocupes, podemos verlo luego poco a poco.

2023-11-04 14:00 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/MainViewModel.kt
> +class MainViewModel(app: Application): AndroidViewModel(app) {
Esta clase la eliminamos de momento ya que podemos implementar una navegación del bottomBar sin necesidad de depender de un View model

2023-11-04 14:15 UTC, Mj-br commented
@JuJoDevs 

Al final he implementado la navegación de una manera un poco diferente a lo que vi en tu repositorio de Marvel, si eso luego lo podemos cambiar. 

Puedes ver el BottomNavigationBar como está, he agregado algunas líneas para controlar el BackStack de la aplicación y lo he puesto comentado para explicar el porqué se hizo así. Creo que está chulo y sencillo.

Todo va de lujo, probarlo desde vuestra app cambiando a esta rama y ya si os gusta aprobad la review.

2023-11-04 21:01 UTC, JuJoDevs commented on app/src/main/kotlin/com/architects/pokearch/ui/main/MainScreen.kt
>      /*TODO: Cambiar box por scaffold con bottom bar*/
Deberías quitar este comentario

2023-11-04 21:03 UTC, JuJoDevs requested changes
Quita los comentarios y apruebo 👍

2023-11-04 21:03 UTC, JuJoDevs commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/BottomNavigationBar.kt
> +                        // Pop up to the start destination of the graph to
Estos comentarios no son necesarios haz una limpieza

2023-11-05 12:37 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/main/MainScreen.kt
>      /*TODO: Cambiar box por scaffold con bottom bar*/
Hecho

2023-11-05 12:38 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/BottomNavigationBar.kt
> +                        // Pop up to the start destination of the graph to
Hecho

2023-11-05 13:22 UTC, JuJoDevs submitted a review, later dismissed

2023-11-06 09:29 UTC, Mj-br commented
Resuelto conflictos

2023-11-06 09:30 UTC, Mj-br commented
Revisada ayer con Gabriel. Le doy mi ok.

2023-11-06 09:30 UTC, Mj-br submitted a review, later dismissed

2023-11-06 10:07 UTC, timacosta commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/Navigation.kt
> -        startDestination = NavItem.Main.route
Yo renombraria  fun Navigation() a algo mas meaningful, quizás PokeArchNavHost, o RootNavGraph

2023-11-06 10:26 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/Navigation.kt
> -        startDestination = NavItem.Main.route
Le pondré PokeArchNavHost

2023-11-06 10:29 UTC, Mj-br approved these changes

2023-11-06 11:07 UTC, timacosta commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/BottomNavigationBar.kt
> +                    navController.navigate(item.navCommand.route) {
Mola, quizás podríamos sacar todo esto a una función aparte llamada navigateToTopLevelDestination

2023-11-06 11:13 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/main/MainScreen.kt
>  fun MainScreen(modifier: Modifier = Modifier, onNavigationDetailClick:(pokemonId: Int) -> Unit){
Esto me parece tiene que ver con el Detekt, es de otra pull request. Si no os parece lo quitamos pero hay que definir esto bien porque en muchos sitios se ha puesto este Modifier por el Detekt. Que hacemos entonces, lo quitamos o lo dejamos? @JuJoDevs @Gascanio101 @timacosta

2023-11-06 11:18 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/NavItem.kt
> +    object Feature : NavCommand("featureScreen")
Sii, esto lo hable con @JuJoDevs cuando se hizo la navegación, olvidé cambiarlo al final. Lo hago ahora.

2023-11-06 11:25 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/navigation/BottomNavigationBar.kt
> +                    navController.navigate(item.navCommand.route) {
Guay, sería una función de extensión de NavOptionsBuilder. Lo implemento.

2023-11-06 11:30 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/ui/main/MainScreen.kt
>  fun MainScreen(modifier: Modifier = Modifier, onNavigationDetailClick:(pokemonId: Int) -> Unit){
Vale, he cambiado el modifier (del box, este estaba usando su propio parametro modifier.) por el modifier que recomienda el Detekt (el del mainScreen que es el que le hemos puesto).

2023-11-06 16:04 UTC, Mj-br approved these changes

2023-11-06 16:05 UTC, merged