46 - Shimmer Effect
timacosta/PokeArch pull request #47
Opened 2023-11-18 17:21 UTC by timacosta

🎩 How was this resolved?

2023-11-19 00:05 UTC, JuJoDevs commented on app/src/main/kotlin/com/architects/pokearch/ui/home/HomeItem.kt
> +        ArchAsyncImage(asyncImagePainter = image, contentDescription = name)
El elemento ArchAsyncImage controla los 4 estados del AsyncImagePainter, no deberías meterlo dentro de ArchAsyncImage?

2023-11-19 00:07 UTC, JuJoDevs commented on app/src/main/kotlin/com/architects/pokearch/ui/components/image/ArchAsyncImage.kt
> +        is AsyncImagePainter.State.Loading -> {}
No sería más lógico poner el ShimmerEffect aquí en vez de controlar en dos sitios distintos el state?

2023-11-19 00:11 UTC, JuJoDevs requested changes
Aparte del pequeño cambio que comento de que ya se controla el state loading dentro del AsyncImagePainter, todo parece estar de 10, muy chulo el efecto

2023-11-20 17:53 UTC, timacosta commented on app/src/main/kotlin/com/architects/pokearch/ui/home/HomeItem.kt
> +        ArchAsyncImage(asyncImagePainter = image, contentDescription = name)
Seria lo ideal, pero dado que el Shimmer Effect hay que aplicarlo, no solo al componente de la Imagen, sino también en la Card / Container, necesitamos tener acceso al state desde fuera. Porque el Shimmer Effect por ahora se aplica a cada componente individualmente. Si la Imagen fuese un componente único entonces si. No se me ocurre ninguna forma sencilla de aplicar esa lógica desde dentro del AsyncImage...

2023-11-20 17:56 UTC, Mj-br approved these changes

2023-11-20 18:06 UTC, timacosta commented on app/src/main/kotlin/com/architects/pokearch/ui/components/image/ArchAsyncImage.kt
> +        is AsyncImagePainter.State.Loading -> {}
Same here. Se podia exponer el state de dentro del Composable con una Lambda o un State en el viewModel, pero hacerlo con una lambda no resuelve el problema. Y añadir un state extra solo para poder exponer el estado de dentro del AsyncImage, es un poco too much, diria yo. Se podría cambiar la estructura y el anidamiento de este componente para que fuese asi, pero como veáis.

2023-11-25 10:26 UTC, Mj-br approved these changes

2023-11-25 10:26 UTC, merged