45 play audio cries
timacosta/PokeArch pull request #49
Opened 2023-11-20 22:57 UTC by JuJoDevs

🎩 How was this resolved?

Se ha añadido un método en el repositorio para recuperar la url de los audios.
![image](https://github.com/timacosta/PokeArch/assets/8354559/d2af9c78-b78e-4645-95fa-79612bcd3577)

El viewmodel ahora recupera el id del Pokémon mediante el savedStateHandle que nos provee viewmodelHilt. Ya no es necesario pasarle el id a la pantalla.
![image](https://github.com/timacosta/PokeArch/assets/8354559/dc07460c-191c-46f3-8754-4ad45957f51e)

Método para recuperar la url del audio en el viewmodel.
![image](https://github.com/timacosta/PokeArch/assets/8354559/ec3af64d-55e6-40cd-975d-a1988a9cba13)

Creo la clase DetailState para abstraer todo lo necesario para reproducir el audio.
![image](https://github.com/timacosta/PokeArch/assets/8354559/7cee4348-dcc1-48a2-8823-d0dd70821257)

Los métodos para configurar y reproducir el audio mediante MediaPlayer.
![image](https://github.com/timacosta/PokeArch/assets/8354559/b29cdfea-cfe1-46bb-b8ae-0f26fe5a4ffb)

El método que lanza el audio en otro hilo y controla que solo se haga una vez (en cada recomposición por rotación volvía a sonar)
![image](https://github.com/timacosta/PokeArch/assets/8354559/0b86bf87-8222-4266-a411-556b7de97a36)

El sonido se reproduce si el uiState es Success
![image](https://github.com/timacosta/PokeArch/assets/8354559/5d2aca27-8ae5-4735-8fb5-401333d97ba7)

2023-11-25 11:44 UTC, Mj-br requested changes

2023-11-25 11:44 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/core/data/repository/PokeArchRepository.kt
> +    override fun fetchCry(name: String) = "$PREFIX_URL$name$SUBFIX_URL"
Esta super bien todo. Se siente bastante bien abrir las imágenes y que suene el sonido del Pokémon.

**Solo hay un detalle pequeñito:** 
- Al abrir pokémons con nombres como nidoran-m o nidoran-f o por ejemplo Ho-oh no suena el pokémon y es porque cuando va y coge el mp3 no lo consigue ya que lo que consigue es nidoranm o nidoranf o Hooh

Probablemente lo puedas solucionar desde acá mismo ->
`override fun fetchCry(name: String) = "$PREFIX_URL$name$SUBFIX_URL"` 

De momento esa función no está considerando este efecto.

2023-11-25 11:44 UTC, Mj-br commented on app/src/main/kotlin/com/architects/pokearch/core/data/repository/PokeArchRepository.kt
> +    override fun fetchCry(name: String) = "$PREFIX_URL$name$SUBFIX_URL"
O quizá lo puedas solucionar desde otra línea de código también, en la interfaz por ejemplo. No sé cual opinas que sería el adecuado a cambiar.

2023-11-25 18:18 UTC, JuJoDevs commented on app/src/main/kotlin/com/architects/pokearch/core/data/repository/PokeArchRepository.kt
> +    override fun fetchCry(name: String) = "$PREFIX_URL$name$SUBFIX_URL"
Como el MediaPlayer tarda tanto en fallar he tenido que crear una consulta con un nuevo service de retrofit para comprobar si existe el endpoint, quizás se pueda simplicar más, pero ahora funcionan los pokemons con guiones.
Voy a repasar el tema de girar la pantalla y os pido que reviséis de nuevo.

2023-11-25 21:43 UTC, Mj-br submitted a review, later dismissed
Ahora si suenan todos los pokémon. Buenaaa!

2023-12-02 23:05 UTC, timacosta approved these changes

2023-12-02 23:37 UTC, Mj-br approved these changes

2023-12-02 23:38 UTC, merged